language: python
python:
  - "2.7"
  - "pypy"  # PyPy2 2.5.0
install:
  - pip install -r requirements.txt
  - pip install -r test/requirements.txt
script: pytest --cov=rplugin/python/neovim_python_debugger test
